---
id: 2025-05-16-open_source_salon_153-rubykaigi2025report
base_name: rubykaigi2025report
tags:
- ruby
- rubykaigi
- rubykaigi2025
presentation_date: '2025-05-16'
presentation_start_time:
presentation_end_time:
version: 2025.5.16.0
licenses:
- CC-BY-4.0
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1368
height: 768
source_code_uri:
author:
  markup_language: :markdown
  name: Yuya.Nishida.
  email:
  rubygems_user: nishidayuya
  slideshare_user:
  speaker_deck_user: nishidayuya
